Update cooks
Laursen79/cooks pull request #2
Opened 2023-05-01 07:49 UTC by Laursen79

2023-05-01 08:00 UTC, t-lohse requested changes

2023-05-01 08:00 UTC, t-lohse commented on cooks
> +1/5  - 23: Lohse
```suggestion
2/5 - 23: Lohse
```

2023-05-01 10:01 UTC, alexsteffensen approved these changes
LGTM

2023-05-01 11:45 UTC, JE-FH commented
review was not good enugh

2023-05-01 11:47 UTC, alexsteffensen approved these changes

2023-05-01 12:11 UTC, t-lohse requested changes

2023-05-01 12:11 UTC, t-lohse commented on cooks
>  4/4  - 23: Simon & Joms
```suggestion
4/4 - 23: Simon & Joms
```

2023-05-09 07:39 UTC, KiraStaehr approved these changes

2023-05-09 07:40 UTC, t-lohse requested changes
Pls also add what dish was served each day

2023-05-09 07:40 UTC, t-lohse commented on cooks
> +4/4 - 23: Simon & Joms
```suggestion
4/4  - 23: Simon & Joms
```

2023-05-09 07:40 UTC, t-lohse commented on cooks
> +2/5 - 23: Lohse
```suggestion
2/5  - 23: Lohse
```

2023-05-09 07:47 UTC, Laursen79 commented
> Pls also add what dish was served each day

I think this would be a bit much, but anyone is welcome to do it. I have created a seperate issue for this.

2023-05-09 10:17 UTC, t-lohse approved these changes
Looks good to DEEZE NUTS

2023-05-09 10:19 UTC, merged