Update README.md
Laursen79/cooks pull request #4
Opened 2023-05-01 12:01 UTC by alexsteffensen

2023-05-01 12:13 UTC, t-lohse requested changes

2023-05-01 12:13 UTC, t-lohse commented on README.md
> +# Welcome to Cocks 🍳
```suggestion
# Welcome to Cocksuckers 🍳
```

2023-05-01 12:14 UTC, alexsteffensen commented on README.md
> +# Welcome to Cocks 🍳
Ahh very nice. Ahh a a i cum

2023-05-30 09:43 UTC, Laursen79 commented
This is not a meme repo, please don't troll

2023-05-30 09:43 UTC, closed without merging